# Generated by Django 3.1.2 on 2021-02-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('alfa', 'Alfa'), ('beta', 'Beta')], max_length=200)),
                ('seq', models.CharField(db_index=True, max_length=200, unique=True)),
                ('source', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(default='')),
                ('seqcore', models.CharField(db_index=True, default='', max_length=200)),
                ('seqmarked', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Smart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('seq', models.CharField(db_index=True, max_length=200, unique=True)),
                ('source', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(default='')),
                ('seqcore', models.CharField(db_index=True, default='', max_length=200)),
                ('seqmarked', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
