# Generated by Django 3.1.2 on 2021-02-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='end',
            field=models.CharField(choices=[('alfa', 'Alfa'), ('beta', 'Beta')], default='', max_length=200),
        ),
    ]
