# Generated by Django 3.1.2 on 2021-02-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primers', '0002_index_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='end',
            field=models.CharField(choices=[('I7', 'I7'), ('I5', 'I5')], default='', max_length=200),
        ),
    ]
