# Generated by Django 3.1.2 on 2021-04-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='alfa_index2_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='beta_index2_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
