# Generated by Django 3.1.2 on 2021-02-18 12:18

from django.db import migrations, models
import filestorage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.IntegerField(db_index=True, default=0)),
                ('file', models.FileField(upload_to=filestorage.models.path2dir)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
